### ISSUE TITLE
Ensure we have latest builds

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monochrom#20]
not sure of any way to automate easily

genomes.yaml:

```yaml
name: foo
genomes:
  mm:
    taxon: NCBITaxon:10090
    name: Mouse
  hg:
    taxon: NCBITaxon:9606
    name: Human
  dm:
    taxon: NCBITaxon:7227
    name: Drosophila melanogaster
  danRer:
    taxon: NCBITaxon:7955
    name: Danio rerio
  rn:
    taxon: NCBITaxon:10116
    name: Rat
  ce:
    taxon: NCBITaxon:6239
    name: C elegans
  galGal:
    taxon: NCBITaxon:9031
    name: Chicken
taxons:
  NCBITaxon:10090:
    name: Mus musculus
  NCBITaxon:9606:
    name: Homo sapiens
  NCBITaxon:7227:
    name: Drosophila melanogaster
  NCBITaxon:7955:
    name: Danio rerio
  NCBITaxon:10116:
    name: Rattus norvegicus
  NCBITaxon:6239:
    name: Caenorhabditis elegans
```

some of these are copied from dipper. We have most up to date chicken. I just updated human with latest from UCSC but I assume the T2T build there soon
